{% set version = '1.4-0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-qpcr
  version: {{ version|replace("-", "_") }}

source:
  fn: qpcR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/qpcR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/qpcR/qpcR_{{ version }}.tar.gz

  sha256: a95c979862e1f4b68f69af9a1c50ea2062f30469be78c5e21d8bc5e898853809

build:

  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mass
    - r-matrix
    - r-minpack.lm
    - r-rgl
    - r-robustbase
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-mass
    - r-matrix
    - r-minpack.lm
    - r-rgl
    - r-robustbase
    - libgcc  # [not win]

test:
  commands:

    - $R -e "library('qpcR')"  # [not win]
    - "\"%R%\" -e \"library('qpcR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=qpcR
  license: GPL (>= 2)
  summary: Model fitting, optimal model selection and calculation of various features that are
    essential in the analysis of quantitative real-time polymerase chain reaction (qPCR).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
