{% set version = '0.6.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-googleauthr
  version: {{ version|replace("-", "_") }}

source:
  fn: googleAuthR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/googleAuthR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/googleAuthR/googleAuthR_{{ version }}.tar.gz
  sha256: 1f2117f8a0f08530373762f02c8aff0110c12ccb17208712cc2018f0bd194291

build:
  merge_build_host: True  # [win]

  number: 0
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-r6 >=2.1.0
    - r-assertthat >=0.2.0
    - r-digest
    - r-httr >=1.3.1
    - r-jsonlite >=0.9.16
    - r-memoise >=1.1.0

  run:
    - r-base
    - r-r6 >=2.1.0
    - r-assertthat >=0.2.0
    - r-digest
    - r-httr >=1.3.1
    - r-jsonlite >=0.9.16
    - r-memoise >=1.1.0

test:
  commands:

    - $R -e "library('googleAuthR')"           # [not win]
    - "\"%R%\" -e \"library('googleAuthR')\""  # [win]

about:
  home: http://code.markedmondson.me/googleAuthR/
  license: MIT
  summary: Create R functions that interact with OAuth2 Google APIs  <https://developers.google.com/apis-explorer/>
    easily, with auto-refresh and Shiny compatibility.
  license_family: MIT
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
