{% set version = '4.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-statnet.common
  version: {{ version|replace("-", "_") }}

source:
  fn: statnet.common_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/statnet.common_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/statnet.common/statnet.common_{{ version }}.tar.gz

  sha256: 206e1967df661b277c6fde68f8b0bf4589508f569ff94f1ec5126c4c56a1867b

build:

  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - libgcc  # [not win]

test:
  commands:

    - $R -e "library('statnet.common')"  # [not win]
    - "\"%R%\" -e \"library('statnet.common')\""  # [win]

about:
  home: http://www.statnet.org
  license: GPL-3
  summary: Non-statistical utilities used by the software developed by the Statnet Project. They
    may also be of use to others.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
