{% set version = '1.1.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-c3net
  version: {{ version|replace("-", "_") }}

source:
  fn: c3net_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/c3net_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/c3net/c3net_{{ version }}.tar.gz

  sha256: 8260569962f2d91ec6627f226d3949f271cc2cfd03886ad854b4ce4074de9654

build:

  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-igraph

  run:
    - r-base
    - r-igraph

test:
  commands:

    - $R -e "library('c3net')"  # [not win]
    - "\"%R%\" -e \"library('c3net')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=c3net
  license: GPL (>= 3)
  summary: This package allows inferring gene regulatory networks with direct physical interactions
    from microarray expression data using C3NET.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}\/lib\/R\/share\/licenses\/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]
extra:
   recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
